module APIConnection {

    interface Client {
        void displayShowInfo(in string showJsonResponse);
        void displayShowEpisodes(in string episodesJsonResponse);
        void displayShowSeasons(in string seasonsJsonResponse);
        void displayShowCast(in string castJsonResponse);
        void displayShowEpisodesByNum(in string epByNumJsonResponse);
    };
    
    interface TVMaze {
        void getShow(in long id, in Client client);
        void getShowEpisodeList(in long id, in Client client);
        void getShowSeasonsList(in long id, in Client client);
        void getShowCastList(in long id, in Client client);
        void getShowEpisodesByNum(in long id, in long season, in long num, in Client client);
    };  
};