package APIConnection;


/**
* APIConnection/_ClientImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from API.idl
* 03 April 2016 19:45:53 o'clock IST
*/

public abstract class _ClientImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements APIConnection.Client, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _ClientImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("displayShowInfo", new java.lang.Integer (0));
    _methods.put ("displayShowEpisodes", new java.lang.Integer (1));
    _methods.put ("displayShowSeasons", new java.lang.Integer (2));
    _methods.put ("displayShowCast", new java.lang.Integer (3));
    _methods.put ("displayShowEpisodesByNum", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // APIConnection/Client/displayShowInfo
       {
         String showJsonResponse = in.read_string ();
         this.displayShowInfo (showJsonResponse);
         out = $rh.createReply();
         break;
       }

       case 1:  // APIConnection/Client/displayShowEpisodes
       {
         String episodesJsonResponse = in.read_string ();
         this.displayShowEpisodes (episodesJsonResponse);
         out = $rh.createReply();
         break;
       }

       case 2:  // APIConnection/Client/displayShowSeasons
       {
         String seasonsJsonResponse = in.read_string ();
         this.displayShowSeasons (seasonsJsonResponse);
         out = $rh.createReply();
         break;
       }

       case 3:  // APIConnection/Client/displayShowCast
       {
         String castJsonResponse = in.read_string ();
         this.displayShowCast (castJsonResponse);
         out = $rh.createReply();
         break;
       }

       case 4:  // APIConnection/Client/displayShowEpisodesByNum
       {
         String epByNumJsonResponse = in.read_string ();
         this.displayShowEpisodesByNum (epByNumJsonResponse);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:APIConnection/Client:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _ClientImplBase
