package APIConnection;


/**
* APIConnection/_TVMazeImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from API.idl
* 03 April 2016 19:45:53 o'clock IST
*/

public abstract class _TVMazeImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements APIConnection.TVMaze, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _TVMazeImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getShow", new java.lang.Integer (0));
    _methods.put ("getShowEpisodeList", new java.lang.Integer (1));
    _methods.put ("getShowSeasonsList", new java.lang.Integer (2));
    _methods.put ("getShowCastList", new java.lang.Integer (3));
    _methods.put ("getShowEpisodesByNum", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // APIConnection/TVMaze/getShow
       {
         int id = in.read_long ();
         APIConnection.Client client = APIConnection.ClientHelper.read (in);
         this.getShow (id, client);
         out = $rh.createReply();
         break;
       }

       case 1:  // APIConnection/TVMaze/getShowEpisodeList
       {
         int id = in.read_long ();
         APIConnection.Client client = APIConnection.ClientHelper.read (in);
         this.getShowEpisodeList (id, client);
         out = $rh.createReply();
         break;
       }

       case 2:  // APIConnection/TVMaze/getShowSeasonsList
       {
         int id = in.read_long ();
         APIConnection.Client client = APIConnection.ClientHelper.read (in);
         this.getShowSeasonsList (id, client);
         out = $rh.createReply();
         break;
       }

       case 3:  // APIConnection/TVMaze/getShowCastList
       {
         int id = in.read_long ();
         APIConnection.Client client = APIConnection.ClientHelper.read (in);
         this.getShowCastList (id, client);
         out = $rh.createReply();
         break;
       }

       case 4:  // APIConnection/TVMaze/getShowEpisodesByNum
       {
         int id = in.read_long ();
         int season = in.read_long ();
         int num = in.read_long ();
         APIConnection.Client client = APIConnection.ClientHelper.read (in);
         this.getShowEpisodesByNum (id, season, num, client);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:APIConnection/TVMaze:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _TVMazeImplBase
