package APIConnection;


/**
* APIConnection/Client_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from API.idl
* 03 April 2016 19:45:53 o'clock IST
*/

public class Client_Tie extends _ClientImplBase
{

  // Constructors
  public Client_Tie ()
  {
  }

  public Client_Tie (APIConnection.ClientOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void displayShowInfo (String showJsonResponse)
  {
    _impl.displayShowInfo(showJsonResponse);
  } // displayShowInfo

  public void displayShowEpisodes (String episodesJsonResponse)
  {
    _impl.displayShowEpisodes(episodesJsonResponse);
  } // displayShowEpisodes

  public void displayShowSeasons (String seasonsJsonResponse)
  {
    _impl.displayShowSeasons(seasonsJsonResponse);
  } // displayShowSeasons

  public void displayShowCast (String castJsonResponse)
  {
    _impl.displayShowCast(castJsonResponse);
  } // displayShowCast

  public void displayShowEpisodesByNum (String epByNumJsonResponse)
  {
    _impl.displayShowEpisodesByNum(epByNumJsonResponse);
  } // displayShowEpisodesByNum

  private APIConnection.ClientOperations _impl;

} // class Client_Tie
