package APIConnection;


/**
* APIConnection/TVMazeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from API.idl
* 03 April 2016 19:45:53 o'clock IST
*/

public interface TVMazeOperations 
{
  void getShow (int id, APIConnection.Client client);
  void getShowEpisodeList (int id, APIConnection.Client client);
  void getShowSeasonsList (int id, APIConnection.Client client);
  void getShowCastList (int id, APIConnection.Client client);
  void getShowEpisodesByNum (int id, int season, int num, APIConnection.Client client);
} // interface TVMazeOperations
